version: '3.8'

services:
  backend:
    build: ./PortfolioApi
    ports:
      - "5050:80"   # Host:Container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDBSettings__ConnectionString=mongodb+srv://portfolio_user_yogesh:StrongPassword123!@protfoliohub.wrdtjl2.mongodb.net/?retryWrites=true&w=majority&appName=protfoliohub
      - MongoDBSettings__DatabaseName=portfoliohub

  frontend:
    build: ./portfolio-frontend
    ports:
      - "5173:80"   # Host:Container
    depends_on:
      - backend